name: Build iOS (Debug)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Tuist
        run: brew install tuist@4.50.2

      - name: Install dependencies
        run: |
          tuist install

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Build iOS app (Debug)
        run: |
          xcodebuild \
            -workspace EkyPOSLocal.xcworkspace \
            -scheme EkyPOSLocal \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.2' \
            build